M48
; DRILL file {KiCad (6.0.1-0)} date Monday, September 18, 2023 at 04:52:35 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-18T16:52:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
%
G90
G05
T1
X53.34Y-93.98
X55.88Y-53.34
X99.06Y-60.96
X99.06Y-93.98
T0
M30
